#!/bin/bash

# Byte-code full absolute path
bc="`pwd`/$1"

# Change to script locate dir
cd "$(dirname "$0")"

# Unset options
unset JAVA_TOOL_OPTIONS
# Export the call graph to temp file
opt -print-callgraph $bc 2>__callgraph.tmp >/dev/null
java -Xmx64m -cp 'bin:pi/bin' ca.uwaterloo.pi.Main "`pwd`/__callgraph.tmp" $2 $3
exitcode=$?
# echo "Bug Detector exit with status code $exitcode"
rm -f __callgraph.tmp
exit $exitcode

